# Generated by Django 3.1.1 on 2020-09-12 12:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('overview', models.TextField(max_length=155)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('featured', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
